[package]
name = "evil_numbers_benchmark"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.70"
publish = false


[dependencies]
eframe = "0.23.0"
env_logger = "0.10"
